# Generated by Django 4.2 on 2023-05-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='zipcode',
        ),
    ]
